### ISSUE TITLE
"Community" page contains broken Markdown code

### ISSUE THREAD

**Issue by kappa7194** [redis/redis-website#19]
The "Community" page available at https://redis.io/community/ contains broken Mardown code in the "Contributing to docs" section:

![community](https://user-images.githubusercontent.com/1249988/160586705-7f404c0b-d9eb-46ed-a347-0c10b64c11c2.png)

**Comment by Raman-Kumar** [comment]
@kappa7194 this has been fixed 
may close it 
@itamarhaber
